### ISSUE TITLE
Cannot compile `eccodes`

### ISSUE THREAD

**Issue by aroblast** [ScaleWeather/eccodes#4]
**Describe the bug**
After following documentation, command `cargo build` crashed with the following error:

```
error[E0432]: unresolved import `eccodes_sys::_IO_FILE`
  --> /Users/bastienlecorre/.cargo/registry/src/index.crates.io-6f17d22bba15001f/eccodes-0.6.9/src/intermediate_bindings.rs:17:27
   |
   |     CODES_TYPE_UNDEFINED, _IO_FILE,
   |                           ^^^^^^^^ no `_IO_FILE` in the root
```

**To Reproduce**
1. `cargo add eccodes`
2. `cargo build`

**Expected behavior**
The compile process should finish successfully.

**Screenshots**

<img width="1003" alt="Screenshot 2023-10-19 at 23 51 43" src="https://github.com/ScaleWeather/eccodes/assets/30211895/ea931477-b60f-4dab-8ece-b521310713a5">

**Desktop**
 - OS: MacOS
 - Version: Sonoma 14.0

**Additional context**
New to Rust, maybe an error on my part?

**Comment by aroblast** [comment]
Forgot to add, I understand this crate is only meant for Linux distros. What's a bit frustrating is that this library seems to compile fine, the problem is that `_IO_FILE` might be from a C header that doesn't get "transpiled" (don't really know if the term is correct here) into the struct definitions expected in the docs bindings. Maybe you have an idea about what to do regarding that? Thanks in advance!

**Comment by Quba1** [comment]
Hi! Thanks for opening this issue. The problem has been already spotted [here](https://github.com/ScaleWeather/eccodes/commit/415cbd60e5bd712912ea59aec2d559418a7b1677). But I haven't addressed it because I don't own a Mac so testing is an issue. I also believe that eccodes devs also officially support only Linux, so I never really bothered to provide MacOS support.

However, the issue seems to be mostly two lines of code: one importing the type from bindings generated by bindgen and the other using that type. In theory then, this could be resolved using conditional compilation in those two lines.

If you need this working quickly you can make necessary changes and add testing for MacOS in Github Actions and create a pull request. I will be able to review that rather soon. Otherwise, you'll need to wait for me to push the changes.

**Comment by Quba1** [comment]
Thank you for your patience. Your suggestions have now been merged and published on [crates.io](crates.io). I hope this works for you now.

Thank you for your contribution.
